# Generated by Django 4.0.7 on 2022-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200, verbose_name='Ид заказа')),
                ('cost_dollars', models.FloatField(verbose_name='Стоимость в долларах')),
                ('cost_rubles', models.FloatField(verbose_name='Стоимость в рублях')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
