# Generated by Django 4.0.7 on 2022-08-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Уведомление отправлено?')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.notificationsreceiver', verbose_name='Получатель сообщения')),
            ],
            options={
                'verbose_name': 'Уведомление о заказе',
                'verbose_name_plural': 'Уведомления о заказах',
            },
        ),
    ]
